use presidentialElection;


INSERT INTO state (state_id, state_name, region)
VALUES (1, 'Alabama', 'SOUTH'),
       (2, 'Alaska', 'OTHER'),
       (3, 'Arizona', 'WEST'),
       (4, 'Arkansas', 'SOUTH'),
       (5, 'California', 'WEST'),
       (6, 'Colorado', 'WEST'),
       (7, 'Connecticut', 'NEW ENGLAND'),
       (8, 'Delaware', 'MID-ATLANTIC'),
       (9, 'Florida', 'SOUTH'),
       (10, 'Georgia', 'SOUTH'),
       (11, 'Hawaii', 'OTHER'),
       (12, 'Idaho', 'WEST'),
       (13, 'Illinois', 'MIDWEST'),
       (14, 'Indiana', 'MIDWEST'),
       (15, 'Iowa', 'MIDWEST'),
       (16, 'Kansas', 'GREAT PLAINS'),
       (17, 'Kentucky', 'SOUTH'),
       (18, 'Louisiana', 'SOUTH'),
       (19, 'Maine', 'NEW ENGLAND'),
       (20, 'Maryland', 'MID-ATLANTIC'),
       (21, 'Massachusetts', 'NEW ENGLAND'),
       (22, 'Michigan', 'MIDWEST'),
       (23, 'Minnesota', 'MIDWEST'),
       (24, 'Mississippi', 'SOUTH'),
       (25, 'Missouri', 'MIDWEST'),
       (26, 'Montana', 'GREAT PLAINS'),
       (27, 'Nebraska', 'GREAT PLAINS'),
       (28, 'Nevada', 'WEST'),
       (29, 'New Hampshire', 'NEW ENGLAND'),
       (30, 'New Jersey', 'MID-ATLANTIC'),
       (31, 'New Mexico', 'WEST'),
       (32, 'New York', 'MID-ATLANTIC'),
       (33, 'North Dakota', 'GREAT PLAINS'),
       (34, 'North Carolina', 'SOUTH'),
       (35, 'Ohio', 'MIDWEST'),
       (36, 'Oklahoma', 'GREAT PLAINS'),
       (37, 'Oregon', 'WEST'),
       (38, 'Pennsylvania', 'MID-ATLANTIC'),
       (39, 'Rhode Island', 'NEW ENGLAND'),
       (40, 'South Carolina', 'SOUTH'),
       (41, 'South Dakota', 'GREAT PLAINS'),
       (42, 'Tennessee', 'SOUTH'),
       (43, 'Texas', 'SOUTH'),
       (44, 'Utah', 'WEST'),
       (45, 'Vermont', 'NEW ENGLAND'),
       (46, 'Virginia', 'SOUTH'),
       (47, 'Washington', 'WEST'),
       (48, 'West Virginia', 'SOUTH'),
       (49, 'Wisconsin', 'MIDWEST'),
       (50, 'Wyoming', 'GREAT PLAINS'),
       (51, 'District of Columbia', 'MID-ATLANTIC');
       

SELECT *
FROM state;